name: workflow1
on: push
jobs:
  lint:  
    runs-on: ubuntu-latest
    steps: 
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Node-setup
        uses: : actions/setup-node@v4
        with: 
          node:-verison: 24

      - name: Install Dependencies
        runs: npm  install

